module.exports = {
  application_domain: 'pacslack.tk',
  log_path: 'logs/',
  log_ext: '.txt',
  icon: 'icon',
  image: 'image',
  invis: 'is-invisible',
  active: 'is-active',
  loading: 'is-loading',
  invalid_elem: 'validation-fail',
  image_suffix: '-image',
  icon_suffix: '-icon',
  placeholder_icon: 'placeholderIcon',
  placeholder_image: 'placeholderImage',
  tab_suffix: '-tab',
  content_suffix: '-content',
  success_notification: 'notification is-success',
  failure_notification: 'notification is-danger',
  posted_message: 'Your message has been sent!',
  not_posted_message: '[MESSAGE FAILURE] There was an error with your request: ',
  code_success: 2000,
  code_invalid_request: 2001,
  code_server_error: 2002,
  code_server_rejected: 2003,
  code_unknown_error: 2999,
}
